/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/media/enrollments/{enrollment_id}/lessons/{lesson_id}/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Asset */
        get: operations["asset_api_v1_media_enrollments__enrollment_id__lessons__lesson_id__assets__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/recording-offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Offer */
        post: operations["offer_api_v1_media_recording_offers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recordings */
        get: operations["recordings_api_v1_media_recordings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/recordings/{recording_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_v1_media_recordings__recording_id__post"];
        /** Erase */
        delete: operations["erase_api_v1_media_recordings__recording_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Accepted */
        Accepted: {
            /**
             * Status
             * @constant
             */
            status: "accepted";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OfferInput */
        OfferInput: {
            /** Activity Id */
            activity_id: string;
            /**
             * Attempt Id
             * Format: uuid
             */
            attempt_id: string;
            /** Consent */
            consent: boolean;
            /**
             * Policy Version
             * @constant
             */
            policy_version: "voice-1";
        };
        /** OfferView */
        OfferView: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Policy Version
             * @default voice-1
             * @constant
             */
            policy_version: "voice-1";
            /**
             * Purpose
             * @default speaking_response_processing
             * @constant
             */
            purpose: "speaking_response_processing";
            /**
             * Retention Until
             * Format: date-time
             */
            retention_until: string;
            /** Selected */
            selected: boolean;
        };
        /** RecordingView */
        RecordingView: {
            /**
             * Consented At
             * Format: date-time
             */
            consented_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Policy Version
             * @default voice-1
             * @constant
             */
            policy_version: "voice-1";
            /**
             * Purpose
             * @default speaking_response_processing
             * @constant
             */
            purpose: "speaking_response_processing";
            /**
             * Retention Until
             * Format: date-time
             */
            retention_until: string;
            /** Uploaded */
            uploaded: boolean;
        };
        /** UploadInput */
        UploadInput: {
            /** Audio Base64 */
            audio_base64: string;
            /**
             * Mime Type
             * @enum {string}
             */
            mime_type: "audio/webm" | "audio/ogg" | "audio/mp4" | "audio/wav";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    asset_api_v1_media_enrollments__enrollment_id__lessons__lesson_id__assets__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollment_id: string;
                lesson_id: string;
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    offer_api_v1_media_recording_offers_post: {
        parameters: {
            query?: never;
            header: {
                "X-NorskAllstars-Client": "web" | "android" | "operator";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recordings_api_v1_media_recordings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingView"][];
                };
            };
        };
    };
    upload_api_v1_media_recordings__recording_id__post: {
        parameters: {
            query?: never;
            header: {
                "X-NorskAllstars-Client": "web" | "android" | "operator";
            };
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    erase_api_v1_media_recordings__recording_id__delete: {
        parameters: {
            query?: never;
            header: {
                "X-NorskAllstars-Client": "web" | "android" | "operator";
            };
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
