// Generated by scripts/android_contract.py. Do not edit.
package com.norskallstars.platform.data

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

@Serializable
data class IdentityAccepted(
    val status: String,
) {
    override fun toString(): String = "IdentityAccepted(redacted)"
}

@Serializable
data class IdentityAccountView(
    val email: String,
    val email_verified: Boolean,
    val id: String,
    val interface_language: String,
    val sign_in_methods: List<String>,
) {
    override fun toString(): String = "IdentityAccountView(redacted)"
}

@Serializable
data class IdentityAuthorizedChange(
    val reauthentication_token: String,
) {
    override fun toString(): String = "IdentityAuthorizedChange(redacted)"
}

@Serializable
data class IdentityEmailRequest(
    val email: String,
) {
    override fun toString(): String = "IdentityEmailRequest(redacted)"
}

@Serializable
data class IdentityErrorDetail(
    val code: String,
    val request_id: String,
) {
    override fun toString(): String = "IdentityErrorDetail(redacted)"
}

@Serializable
data class IdentityErrorResponse(
    val error: IdentityErrorDetail,
) {
    override fun toString(): String = "IdentityErrorResponse(redacted)"
}

@Serializable
data class IdentityGoogleChallenge(
    val client_id: String,
) {
    override fun toString(): String = "IdentityGoogleChallenge(redacted)"
}

@Serializable
data class IdentityGoogleChallengeView(
    val challenge: String,
    val nonce: String,
) {
    override fun toString(): String = "IdentityGoogleChallengeView(redacted)"
}

@Serializable
data class IdentityGoogleLink(
    val challenge: String,
    val id_token: String,
    val reauthentication_token: String,
) {
    override fun toString(): String = "IdentityGoogleLink(redacted)"
}

@Serializable
data class IdentityGoogleProof(
    val challenge: String,
    val id_token: String,
) {
    override fun toString(): String = "IdentityGoogleProof(redacted)"
}

@Serializable
data class IdentityGoogleSignIn(
    val challenge: String,
    val device_label: String,
    val id_token: String,
) {
    override fun toString(): String = "IdentityGoogleSignIn(redacted)"
}

@Serializable
data class IdentityPasswordChange(
    val password: String,
    val reauthentication_token: String,
) {
    override fun toString(): String = "IdentityPasswordChange(redacted)"
}

@Serializable
data class IdentityPasswordReset(
    val password: String,
    val token: String,
) {
    override fun toString(): String = "IdentityPasswordReset(redacted)"
}

@Serializable
data class IdentityPreferences(
    val interface_language: String,
) {
    override fun toString(): String = "IdentityPreferences(redacted)"
}

@Serializable
data class IdentityReauthentication(
    val google: IdentityGoogleProof? = null,
    val password: String? = null,
    val purpose: String,
) {
    override fun toString(): String = "IdentityReauthentication(redacted)"
}

@Serializable
data class IdentityReauthenticationView(
    val expires_in: Int,
    val reauthentication_token: String,
) {
    override fun toString(): String = "IdentityReauthenticationView(redacted)"
}

@Serializable
data class IdentityRefresh(
    val refresh_token: String,
) {
    override fun toString(): String = "IdentityRefresh(redacted)"
}

@Serializable
data class IdentityRegistration(
    val email: String,
    val password: String,
) {
    override fun toString(): String = "IdentityRegistration(redacted)"
}

@Serializable
data class IdentitySessionTokens(
    val access_token: String,
    val expires_in: Int? = null,
    val refresh_token: String,
    val session_id: String,
    val token_type: String? = null,
) {
    override fun toString(): String = "IdentitySessionTokens(redacted)"
}

@Serializable
data class IdentitySessionView(
    val created_at: String,
    val current: Boolean,
    val device_label: String,
    val expires_at: String,
    val id: String,
    val last_used_at: String,
) {
    override fun toString(): String = "IdentitySessionView(redacted)"
}

@Serializable
data class IdentitySignIn(
    val device_label: String,
    val email: String,
    val password: String,
) {
    override fun toString(): String = "IdentitySignIn(redacted)"
}

@Serializable
data class IdentityTokenRequest(
    val token: String,
) {
    override fun toString(): String = "IdentityTokenRequest(redacted)"
}

@Serializable
data class IdentityVerificationRequired(
    val status: String,
) {
    override fun toString(): String = "IdentityVerificationRequired(redacted)"
}

@Serializable
data class LearningActivityView(
    val activity_id: String,
    val choices: List<String>,
    val evaluation_type: String,
    val presentation: LearningPresentation? = null,
    val prompt: String,
    val response_mode: String,
    val rubric: List<String>?,
    val type: String,
) {
    override fun toString(): String = "LearningActivityView(redacted)"
}

@Serializable
data class LearningAssessmentView(
    val activities: List<LearningActivityView>,
    val assessment_version: String,
    val policy_digest: String,
    val policy_version: String,
) {
    override fun toString(): String = "LearningAssessmentView(redacted)"
}

@Serializable
data class LearningAttemptView(
    val active_seconds: Int? = null,
    val completion_credit: Boolean?,
    val evaluations: List<LearningEvaluationView>?,
    val id: String,
    val kind: String,
    val lesson_id: String,
    val lesson_version: String,
    val policy_digest: String,
    val policy_version: String,
    val started_at: String,
    val submitted_at: String?,
) {
    override fun toString(): String = "LearningAttemptView(redacted)"
}

@Serializable
data class LearningBlockView(
    val activity_ref: String?,
    val alt_text: String?,
    val asset_ref: String?,
    val block_id: String,
    val language: String?,
    val order: Int,
    val text: String?,
    val translation_available: Boolean,
    val type: String,
) {
    override fun toString(): String = "LearningBlockView(redacted)"
}

@Serializable
data class LearningChapterView(
    val chapter_id: String,
    val lessons: List<LearningLessonSummary>,
    val title: String,
) {
    override fun toString(): String = "LearningChapterView(redacted)"
}

@Serializable
data class LearningCourseView(
    val course_id: String,
    val course_version: String,
    val language: String,
    val release_id: String,
    val title: String,
) {
    override fun toString(): String = "LearningCourseView(redacted)"
}

@Serializable
data class LearningEngagementInput(
    val sequence: Int,
) {
    override fun toString(): String = "LearningEngagementInput(redacted)"
}

@Serializable
data class LearningEnrollInput(
    val course_id: String,
) {
    override fun toString(): String = "LearningEnrollInput(redacted)"
}

@Serializable
data class LearningEnrollmentSummary(
    val course: LearningCourseView,
    val created_at: String,
    val id: String,
    val policy_digest: String,
    val policy_version: String,
) {
    override fun toString(): String = "LearningEnrollmentSummary(redacted)"
}

@Serializable
data class LearningEnrollmentView(
    val chapters: List<LearningChapterView>,
    val concepts: Map<String, LearningMasteryView>,
    val course: LearningCourseView,
    val created_at: String,
    val id: String,
    val placement_available: Boolean,
    val policy_digest: String,
    val policy_version: String,
    val progress: List<LearningProgressView>,
    val recommended_lesson_id: String?,
) {
    override fun toString(): String = "LearningEnrollmentView(redacted)"
}

@Serializable
data class LearningErrorDetail(
    val code: String,
    val request_id: String,
) {
    override fun toString(): String = "LearningErrorDetail(redacted)"
}

@Serializable
data class LearningErrorResponse(
    val error: LearningErrorDetail,
) {
    override fun toString(): String = "LearningErrorResponse(redacted)"
}

@Serializable
data class LearningEvaluationView(
    val activity_id: String,
    val correct: Boolean?,
    val evaluator: String,
    val evaluator_version: String,
    val normalized: JsonElement,
    val response: JsonElement,
    val score: String?,
    val status: String,
) {
    override fun toString(): String = "LearningEvaluationView(redacted)"
}

@Serializable
data class LearningHistoryInput(
    val before: String? = null,
    val limit: Int? = null,
) {
    override fun toString(): String = "LearningHistoryInput(redacted)"
}

@Serializable
data class LearningHistoryView(
    val attempts: List<LearningAttemptView>,
    val next_before: String?,
) {
    override fun toString(): String = "LearningHistoryView(redacted)"
}

@Serializable
data class LearningLessonSummary(
    val lesson_id: String,
    val title: String,
    val version: String,
) {
    override fun toString(): String = "LearningLessonSummary(redacted)"
}

@Serializable
data class LearningLessonView(
    val activities: List<LearningActivityView>,
    val blocks: List<LearningBlockView>,
    val lesson_id: String,
    val title: String,
    val version: String,
) {
    override fun toString(): String = "LearningLessonView(redacted)"
}

@Serializable
data class LearningMasteryView(
    val score: String?,
    val status: String,
    val value: Boolean?,
) {
    override fun toString(): String = "LearningMasteryView(redacted)"
}

@Serializable
data class LearningPlacementInput(
    val acknowledged: Boolean,
    val operation_id: String,
    val responses: List<LearningResponseInput>,
) {
    override fun toString(): String = "LearningPlacementInput(redacted)"
}

@Serializable
data class LearningPlacementView(
    val assessment_version: String,
    val created_at: String,
    val id: String,
    val policy_digest: String,
    val policy_version: String,
    val recommended_lesson_id: String,
    val score: String,
) {
    override fun toString(): String = "LearningPlacementView(redacted)"
}

@Serializable
data class LearningPresentation(
    val fields: List<String>? = null,
    val kind: String,
    val options: List<LearningResponseOption>,
) {
    override fun toString(): String = "LearningPresentation(redacted)"
}

@Serializable
data class LearningProgressView(
    val available: Boolean,
    val completed_at: String?,
    val completion: String,
    val lesson_id: String,
    val mastery: LearningMasteryView,
    val review_due_at: String?,
) {
    override fun toString(): String = "LearningProgressView(redacted)"
}

@Serializable
data class LearningResponseInput(
    val acknowledged: Boolean,
    val activity_id: String,
    val response: JsonElement,
    val self_assessment: Boolean? = null,
) {
    override fun toString(): String = "LearningResponseInput(redacted)"
}

@Serializable
data class LearningResponseOption(
    val label: String,
    val value: JsonElement,
) {
    override fun toString(): String = "LearningResponseOption(redacted)"
}

@Serializable
data class LearningReviewView(
    val due_at: String,
    val lesson_id: String,
) {
    override fun toString(): String = "LearningReviewView(redacted)"
}

@Serializable
data class LearningStartInput(
    val kind: String,
    val lesson_id: String,
    val operation_id: String,
) {
    override fun toString(): String = "LearningStartInput(redacted)"
}

@Serializable
data class LearningSubmitInput(
    val acknowledged: Boolean,
    val responses: List<LearningResponseInput>,
) {
    override fun toString(): String = "LearningSubmitInput(redacted)"
}

@Serializable
data class LearningTranslationInput(
    val block_id: String,
    val lesson_id: String,
    val operation_id: String,
) {
    override fun toString(): String = "LearningTranslationInput(redacted)"
}

@Serializable
data class LearningTranslationView(
    val reference_text: String,
) {
    override fun toString(): String = "LearningTranslationView(redacted)"
}

@Serializable
data class MediaAccepted(
    val status: String,
) {
    override fun toString(): String = "MediaAccepted(redacted)"
}

@Serializable
data class MediaHTTPValidationError(
    val detail: List<MediaValidationError>? = null,
) {
    override fun toString(): String = "MediaHTTPValidationError(redacted)"
}

@Serializable
data class MediaOfferInput(
    val activity_id: String,
    val attempt_id: String,
    val consent: Boolean,
    val policy_version: String,
) {
    override fun toString(): String = "MediaOfferInput(redacted)"
}

@Serializable
data class MediaOfferView(
    val expires_at: String,
    val id: String,
    val policy_version: String? = null,
    val purpose: String? = null,
    val retention_until: String,
    val selected: Boolean,
) {
    override fun toString(): String = "MediaOfferView(redacted)"
}

@Serializable
data class MediaRecordingView(
    val consented_at: String,
    val id: String,
    val policy_version: String? = null,
    val purpose: String? = null,
    val retention_until: String,
    val uploaded: Boolean,
) {
    override fun toString(): String = "MediaRecordingView(redacted)"
}

@Serializable
data class MediaUploadInput(
    val audio_base64: String,
    val mime_type: String,
) {
    override fun toString(): String = "MediaUploadInput(redacted)"
}

@Serializable
data class MediaValidationError(
    val ctx: JsonElement? = null,
    val input: JsonElement? = null,
    val loc: List<JsonElement>,
    val msg: String,
    val type: String,
) {
    override fun toString(): String = "MediaValidationError(redacted)"
}
