"""Generate Kotlin response DTOs from accepted API schemas; --check detects drift."""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / "apps/android/app/src/main/java/com/norskallstars/platform/data/Contract.kt"


def generate():
    lines = [
        "// Generated by scripts/android_contract.py. Do not edit.",
        "package com.norskallstars.platform.data",
        "",
        "import kotlinx.serialization.Serializable",
        "import kotlinx.serialization.json.JsonElement",
        "",
    ]
    for prefix, name in (("Identity", "identity"), ("Learning", "learning"), ("Media", "media")):
        schemas = json.loads((ROOT / f"contracts/api/{name}-v1.openapi.json").read_text())["components"]["schemas"]

        def kind(s):
            if "$ref" in s:
                if s["$ref"].endswith("/JsonValue"):
                    return "JsonElement"
                return prefix + s["$ref"].split("/")[-1]
            if "anyOf" in s:
                nonnull = [i for i in s["anyOf"] if i.get("type") != "null"]
                value = kind(nonnull[0]) if len(nonnull) == 1 else "JsonElement"
                return value + ("?" if len(nonnull) < len(s["anyOf"]) else "")
            t = s.get("type")
            if t == "array":
                return f"List<{kind(s['items'])}>"
            if t == "object":
                return f"Map<String, {kind(s['additionalProperties'])}>" if isinstance(s.get("additionalProperties"), dict) else "JsonElement"
            return {"string": "String", "integer": "Int", "number": "Double", "boolean": "Boolean"}.get(t, "JsonElement")

        for cls, schema in sorted(schemas.items()):
            props = schema.get("properties")
            if not props:
                continue
            lines.extend(["@Serializable", f"data class {prefix}{cls}("])
            for field, spec in props.items():
                typ = kind(spec)
                optional = field not in schema.get("required", [])
                if optional and not typ.endswith("?"):
                    typ += "?"
                default = " = null" if optional else ""
                lines.append(f"    val {field}: {typ}{default},")
            lines.extend([") {", f'    override fun toString(): String = "{prefix}{cls}(redacted)"', "}", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generate()
    if args.check:
        if not DEST.exists() or DEST.read_text() != content:
            raise SystemExit("Android API DTO drift; run python3 scripts/android_contract.py")
        print("Android API DTOs match all three versioned OpenAPI contracts")
    else:
        DEST.parent.mkdir(parents=True, exist_ok=True)
        DEST.write_text(content)


if __name__ == "__main__":
    main()
